fangfufu/Linux-Fake-Background-Webcam

docker-compose.yml
I personally would prefer to drop all the shell scripts (build.sh, remove-*.sh, ...) and replace them with this single docker-compose.yml file.
Run and initial build containers: `docker-compose up`  (or `docker-compose up -d`)
Stop and remove containers: `docker-compose down`
The compose file can also be edited to map another background image or use different video devices without needing to rebuild the docker images.
=> Add docker compose file.

.gitignore, DOCKER.md, README.md, bodypix/Dockerfile, docker-compose.yml, fakecam/Dockerfile
This adds the docker stuff again and updates most parts (including a `DOCKER.md`) as suggested. I also have changed the network mode to `host` to not require any changes to fake.py (localhost vs. bodypix hostnames in URL).
I do not have NodeJS (12) available on my Debian host neither do I wan't to install a third party repository, so I would like to keep the dockered deployment available.
=> Update readme compose

README.md, fakecam/fake.py
Apologies, I forgot to change an argument name in the previous PR..
Added also a note about v4l2loopback in README.
Signed-off-by: Bigo <bigo@crisidev.org>
=> Fix leftover argument error on main Python object. 

docker-compose.yml
This PR avoid the usage of the host network but instead uses an internal docker network. This way, the port `9000` can be occupied by other processes on the host (as on my machine).
=> Using internal docker network

README.md, bodypix/app.js
By treating the configurable parameters as environment variables, we
can tune and tweak bodypix more during startup.
Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>
=> bodypix: Turn hardcoded defaults into options

docker-compose.yml
This gives better signal handling.
For example:
- Run `docker-compose up`
- When you want to stop it, press `CTRL-c` in the same console.
- It now exits cleanly quickly, instead of very slowly and then abruptly.
Similar example:
- Run `docker-compose up -d`
- When you want to stop it, run `docker-compose down` in another console.
- It now exits cleanly quickly, instead of very slowly and then abruptly.
=> Use tini for quicker exit.

DOCKER.md
This fixes a typo in `DOCKER.md`, so the link is properly closed.
=> Fix link syntax.

bodypix/app.js
There was a partial line of old code causing "node app.js" to fail with a syntax error. Removing this partial line fixes the error.
=> Fix for typo in app.js

fakecam/Dockerfile
Installing `numpy` fails, when we build the Dockerfile of `fakecam`. By switching from debian to the offical Python image, we can select a Python version. With version 3.8 the build runs successfully.
=> Use distinct Python version

install.sh
Install to ~/.local so sudo isn't required (otherwise it would fail) which is aligned with npm installation
Verified by running the script. Deps were installed and cam worked correctly.
=> Update install.sh to not require sudo

fakecam/requirements.txt
opencv-python 4.2.0.32 no longer seems to be available for download from pip. 4.4.0.46 is available and seems to work with a simple background removal test with OBS and Manjaro Linux. 4.4.0.46 requires numpy 1.19.3.
Original error:
`Collecting numpy==1.18.2
Using cached numpy-1.18.2.zip (5.4 MB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing wheel metadata ... done
ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.34 (from -r fakecam/requirements.txt (line 2)) (from versions: 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48)                          
ERROR: No matching distribution found for opencv-python==4.2.0.34 (from -r …
=> Update opencv-python and numpy

docker-compose-nvidia.yml, fakecam/fake.py
Proposed changes to optimize the real camera with the following changes:
1. Set default codec to `MJPG` to get better FPS at higher resolutions. The default detected by many cameras is `YUYV` which limits to 10 fps in many instances
2. Allow for codec to be set in the arg list if desired
3. setting both width and height before checking their validity If both are not set false errors occur
4. Presenting the configurable value before and after setting them
Various scenarios:
Using default settings set in parse_args
```bash
fakecam_1  | 2021-02-21T21:28:44.538579395Z Real camera original values are set as: 640x480 with 30 FPS and video codec 1448695129
fakecam_1  | 2021-02-21T21:28:44.605639190Z Real camera new values are set as: 1280x720 with 30 FPS and video codec 1196444237
fakecam_1  | …
```
=> optimize settings for realcam, allowing for changing codec

fake.py
`foreground_frame` is no longer defined since the code cleanup, which throws a runtime exception. Replaced with an existing variable, which makes the code work.
=> :bug: Make hologram appear again

fake.py, requirements.txt
Consumer detection using inotify enabling ondemand processing as described in  [#119](https://github.com/fangfufu/Linux-Fake-Background-Webcam/issues/119). When started with the command line option --ondemand Linux-Fake-Background tracks the presence of consumers accessing the virtual video device and disables/enables processing based on this. Thus there is no relevant system load when the video stream is not being needed, giving the option of running Linux-Fake-Background in background.
=> Ondemand video processing.

fake.py, install.sh, requirements.txt
I liked this project quite a lot, but wanted to heavily blur my background. The box blur that's done in master branch leads to "banding", which is pretty common with heavy box blurs (since it's unweighted). It's also a bit slow at higher kernel sizes.
This change downsamples first, then runs an iterative gauss blur (using the number of iterations from `background_blur` that users pass in), then upscales with a linear area filter. It went from ~20fps with master to >30fps (my camera doesnt go faster than that) with this branch. 
Here's a before/after of what it looks like for me;
It's most noticeable on the black lamp stem, which appears to be almost two different stems with master branch, and the edge of the chair, which similarly gets "pulled out".
Finally to get it to build i had to …
=> Use iterative-gaussian blur for background

fake.py
I've set the default kernel size to 15px and added another option `--background-blur-sigma-frac` to allow for control of the sigma value, which defaults to 6. I also added an argparse formatter class to add the defaults to the help string.
I tried a combination of kernel sizes (11, 15 and 21 across the columns) and 2 sigma values for each (across the rows):
I prefer either kernel=11, sigma=kernel/3 or kernel=15, sigma=kernel/6. To me, these minimise the halo effect around your head that you get from the blurring. I haven't tested the effects of changing `--threshold` on the halo effect.
In terms of CPU load I found that it doesn't depend on sigma, only on the kernel size (as you'd expect) and concluded that 15 is a fine middle ground. I did the testing with a 640 x 480 px video feed:
| …
=> Gaussian bluring instead of box filter

requirements.txt
As-is, a fresh environment with requirements from `requirements.txt` produces:
```
$ python fake.py -v  /dev/video6  --no-background --no-foreground
Traceback (most recent call last):
File "fake.py", line 17, in <module>
from cmapy import cmap
ModuleNotFoundError: No module named 'cmapy'
```
=> Add cmapy to requirements.txt

.gitignore, benchmark.sh
Ugly script that should help with #160. The script is based on v4l2loopback and creates `/dev/video99` and `/dev/video100`. `ffmpeg` (or `avconv`) is used to loop a [video](https://google.github.io/mediapipe/images/selfie_segmentation_web.mp4) at 1920x1080 to `/dev/video99` with 60 FPS. fake.py is run for 3 minutes while the FPS counter is collected to calculate average and stdev in the end. Additional parameters like `--hologram` can be given to the script and will passed to `fake.py`.
Using a real camera for the benchmark seems unreliable. My USB camera for example claims to deliver images at 30 FPS, which it sometimes does but then suddenly falls back to 15 FPS until I re-plug it.
For 04a4960dc8daad11ac1d7be15cfe1a591c1fdca2 my results look like this:
```
1920x1080@60 for 180 seconds …
```
=> Add benchmark script

fake.py
Querying the inotify watcher causes the camera to freeze momentarily every time it's queried since `load_images()` is called several times when `consumers > 0`.  This moves it to its own thread so it doesn't interrupt the stream.
The primary fix is simply unindenting lines 299:306 pre-patch (101:108 post-patch) which will prevent the momentary freeze, but continuously querying inotify in the same loop as the camera stream noticeably reduces the framerate.
=> Move inotify checks to separate thread

fake.py
Some cameras/frame-grabbers only have one huge resolution (e.g.
1920x1080) which causes a high cpu load when processing the image.
Resize the image prior to processing to the requested size to
significantly reduce the load.
=> Resize camera image before processing

README.md
=> Zoom added Virtual Background without chroma key to linux.

README.md, systemd-user/fakecam.service
Hello,
I was configuring your software on my system and was missing some guide on how-to run it as a systemd service. I figured it out eventually and would like to share the resulting setup. When properly configured, fake.py will be automatically runafter user login by Systemd.
```
systemctl --user status fakecam.service
● fakecam.service - Fake camera
Loaded: loaded (/home/martbab/.config/systemd/user/fakecam.service; enabled; preset: enabled)
Active: active (running) since Tue 2022-08-23 13:04:00 CEST; 1h 49min ago
Main PID: 74667 (python3)
Tasks: 31 (limit: 18908)
Memory: 17.2M
CPU: 3min 932ms
CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/fakecam.service
└─74667 python3 fake.py -c /home/martbab/.config/fakecam/config.ini
Aug 23 13:04:00 neurothrope systemd[894]: …
```
=> Add an example for user systemd service

.github/workflows/codespell.yml, README.md, pyproject.toml
More about codespell: https://github.com/codespell-project/codespell .
I personally introduced it to dozens if not hundreds of projects already and so far only positive feedback.
CI workflow has 'permissions' set only to 'read' so also should be safe.
Congrats on having just a single typo... feel free to drop this PR
=> Add codespell support (config, workflow to detect/not fix) and make it fix a single typo!
