fakecam/Dockerfile
The foreground image files are missing in the Dockerfile.
=> Add missing foreground files to Dockerfile (related to #8).

fakecam/fake.py
* `FakeCam.images["background"]` is now a looping iterator of background images
* first try `cv2.imread` background image, otherwise use `cv2.VideoCapture`
=> added support for animated background

fakecam/fake.py
fakecam_1  | [ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
fakecam_1  | [ERROR:0] global ../modules/videoio/src/cap.cpp (116) open VIDEOIO(GSTREAMER): raised OpenCV exception:
fakecam_1  | 
fakecam_1  | OpenCV(4.2.0) ../modules/videoio/src/cap_gstreamer.cpp:743: error: (-215:Assertion failed) uridecodebin in function 'open'
fakecam_1  | 
fakecam_1  |
=> Need this to fix  error: (-215:Assertion failed)

fakecam/fake.py
This way you can have several folders with different background/foreground and easily choose which to use.
=> Improve image loading and print FPS.

DOCKER.md, README.md
I have updated the `README.md` as per [your request](https://github.com/fangfufu/Linux-Fake-Background-Webcam/issues/13#issuecomment-634649803) with the guide.
=> Add instructions on the installation of v4l2loopback correctly

fakecam/fake.py
Hello
This patch makes tile a small background images.
=> make small images tiled.

fakecam/fake.py
Hologram effect was not working as the function returned the new frame and it was not used.
Option to no set a background image with --no-background. Background will blur. Blur level can be set with --background-blur.
=> Fix hologram effect and add blur background

fakecam/fake.py
I've just installed this tool working and I think it's great! I've made a few minor enhancements/fixes which I'd love you to consider including. Each one is a separate commit.
The main enhancement (first commit) is an option to maintain the background pixel aspect ratio.
The second commit is a fix to calculation of the adv_rate to handle slow frame rate background. For slow movies the adv_rate can round to 0 and so freeze the background movie. My enhancement randomly chooses whether to advance by 0 or 1 frames with a probability that ensures the correct expected frame advance rate over many frames. It leaves the behaviour unchanged when adv_rate>=1.
Comment welcome.
Thanks.
Dan
=> Minor enhancements

Dockerfile
This file no longer exists in the project.
=> Removed akvcam.py from Dockerfile COPY command

fake.py, requirements.txt
Reverts fangfufu/Linux-Fake-Background-Webcam#128
=> Revert "Apply colormaps (like the hologram effect)"

fake.py
- background mask updated with exponential average to avoid flickering
- used sigmoid for a more clear division between the background mask and the frame
=> background-mask-update-speed branch

fake.py
Hello.
When I copied  background.jpeg to fakecam folder and removed background.jpg, fake.py died with Ctrl+C. So I wrote a patch for this problem.
=> Enabled to change extension of foreground/background images.

README.md, v4l2loopback-install.sh
Using instructions from the README
=> created script to setup modprobe files for v4l2loopback

fake.py, install.sh
Reverts fangfufu/Linux-Fake-Background-Webcam#142
=> Revert "Use iterative-gaussian blur for background"

README.md, config-example.ini, fake.py, requirements.txt
Using the ConfigArgParse library we have option parity between args and
config files (ini format)
solves #145
=> Add config file support

fake.py
In my test setup, this improved my frame rate from 10 FPS to around 30 FPS on 1920x1080 when running `./fake.py -w /dev/video99 -v /dev/video100 --threshold 50 -F60` (where /dev/video99 is a v4l2loopback device, delivering at 60 FPS). Functionality should remain unchanged. It's mostly just replacing some of the code with in-place operations.
=> Improve performance

fake.py
Reverts fangfufu/Linux-Fake-Background-Webcam#162
=> Revert "Move inotify checks to separate thread"

fake.py
solves https://github.com/fangfufu/Linux-Fake-Background-Webcam/issues/194
=> Checking if the real cam could be openend before continuing.

README.md, fake.py
Added two selfie effects: blur and solid which render the selfie in a fixed color.
Implement a unified way to specify and implement selfie effects using a simpler but extendable syntax
=> Two new selfie-related filters

lfbw/lfbw.py
Fixes https://github.com/fangfufu/Linux-Fake-Background-Webcam/issues/201
=> Use a shallow copy of segmentation_mask as it's readonly
